server.port: 8090
spring:
  application.name: mail-svc
  kafka:
    bootstrap-servers: 192.168.99.100:9092
    consumer:
      group-id: mail-svc
      value-deserializer: "maandr.starters.deserializer.OrderDeserializer"
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL