server.port: 8091
spring:
  application.name: order-svc
  kafka:
    bootstrap-servers: 192.168.99.100:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "maandr.starters"